# print("Введіть три числа ")
# a = float(input())
# b = float(input())
# c = float(input())
# print("Сума чисел = ", a+b+c)
# print("Добуток чисел = ", a*b*c)

# print("Введіть свою зарплату за місяць: ")
# zp = float(input())
# print("Введіть суму місячного платежу за кредитом у банку: ")
# cr = float(input())
# print("Введіть заборгованість за комунальні послуги: ")
# zb = float(input())
# print("Ваш залишок становить: ", zp-cr-zb)

# print("Введіть довжини двох діагоналей ромба")
# d1 = float(input())
# d2 = float(input())
# print(f"Площа ромба =  {d1*d2*0.5} см**2")